// <copyright file="Occasions.cs" company="Shkyrockett" >
// Copyright © 2005 - 2024 Shkyrockett. All rights reserved.
// </copyright>
// <author id="shkyrockett">Shkyrockett</author>
// <license>
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </license>
// <summary></summary>
// <remarks></remarks>

using Engine.Localization;

namespace Engine.Chrono;

/// <summary>
/// Holidays and special occasions class.
/// </summary>
public class Occasions
{
    /// <summary>
    /// The list of holidays.
    /// </summary>
    public List<Occasion> HolidayList { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Occasions"/> class.
    /// </summary>
    /// <param name="year">The year.</param>
    /// <remarks>
    /// <para>http://www.kenhamady.com/form26.shtml
    /// http://www.kenhamady.com/form25b.shtml</para>
    /// </remarks>
    public Occasions(int year)
    {
        HolidayList =
        [
            // - Floating holidays -
            Occasion.MartinLutherKingDay(year, Cultures.en_US),
            Occasion.PresidentsDay(year, Cultures.en_US),
            Occasion.MothersDay(year, Cultures.en_US),
            Occasion.MemorialDay(year, Cultures.en_US),
            Occasion.FathersDay(year, Cultures.en_US),
            Occasion.LaborDay(year, Cultures.en_US),
            Occasion.ColumbusDay(year),
            Occasion.ElectionDay(year, Cultures.en_US),
            Occasion.ThanksgivingDay(year, Cultures.en_US),
            Occasion.ThanksgivingDay(year, Cultures.en_CA),
            Occasion.ThanksgivingDay(year, Cultures.en_AU),
            Occasion.ThanksgivingDay(year, Cultures.en_GD),
            Occasion.ThanksgivingDay(year, Cultures.en_LR),
            Occasion.GoodFriday(year, Cultures.en_US),
            Occasion.EasterSunday(year, Cultures.en_US),
            Occasion.AscensionDay(year, Cultures.en_US),
            Occasion.FirstSundayOfAdvent(year, Cultures.en_US),
            Occasion.OrthodoxEaster(year, Cultures.en_US),
            Occasion.WhitSunday(year, Cultures.en_US),

            Occasion.DaylightSavingsTimeBegins(year, Cultures.en_US),
            Occasion.DaylightSavingsTimeEnds(year, Cultures.en_US),
            Occasion.TaxDay(year, Cultures.en_US),
            Occasion.FlagDay(year, Cultures.en_US),
            Occasion.IndependenceDay(year, Cultures.en_US),

            // - Local occasions -
            Occasion.BellevueStrawberryDaysStart(year, Cultures.en_US),
            Occasion.BellevueStrawberryDaysEnd(year, Cultures.en_US),
            Occasion.BrighamCityPeachDaysStart(year, Cultures.en_US),
            Occasion.BrighamCityPeachDaysEnd(year, Cultures.en_US),
            Occasion.PioneerDay(year, Cultures.en_US),

            // - Static holidays -
            Occasion.NewYearsDay(year, Cultures.en_US),
            Occasion.GroundhogDay(year, Cultures.en_US),
            Occasion.ValentinesDay(year, Cultures.en_US),
            Occasion.SaintPatrickDay(year, Cultures.en_US),
            Occasion.EuropeanLaborDay(year, Cultures.en_US),
            Occasion.CincoDeMayo(year, Cultures.en_US),
            Occasion.PatriotDay(year, Cultures.en_US),
            Occasion.Halloween(year, Cultures.en_US),
            Occasion.GuyFawkesDay(year, Cultures.en_US),
            Occasion.AllSaintsDay(year, Cultures.en_US),
            Occasion.VeteransDay(year, Cultures.en_US),
            Occasion.ChristmasEve(year, Cultures.en_US),
            Occasion.ChristmasDay(year, Cultures.en_US),
            Occasion.BoxingDay(year, Cultures.en_US),
            Occasion.NewYearsEve(year, Cultures.en_US),
            Occasion.ElvisPresleyBirthday(year),

            new(
                "Pi Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Event,
                new DateTime(year, (int)Month.March, 14),
                "Day to celebrate the irrational number Pi on 3/14."),

            new(
                "Programmer's Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Event,
                new DateTime(year, (int)Month.January, 1).AddDays(255),
                "Day to celebrate Programmers."),

            //Holiday.VernalEquinoxNorthernHemisphere(year, Cultures.en_US),
            //Holiday.SummerSolsticeNorthernHemisphere(year, Cultures.en_US),
            //Holiday.AutumnalEquinoxNorthernHemisphere(year, Cultures.en_US),
            //Holiday.WinterSolsticeNorthernHemisphere(year, Cultures.en_US),

            // - Birthdays -

            Occasion.ElvisPresleyBirthday(year),
            (year <=  1706)? null : new Occasion(
                "Benjamin Franklin's Birthday",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Birthday,
                new DateTime(year, (int)Month.January, 17),
                "The great early American scientist, thinker and statesman. Benjamin Franklin was Born in Boston MA on January 17th, 1706."),
            (year <=  1882)? null : new Occasion(
                "Franklin Delano Roosevelt's Birthday",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Birthday,
                new DateTime(year, (int)Month.January, 30),
                "The 32nd president of the United States. Franklin Delano Roosevelt was born in New York on January 30th, 1882."),
            (year <=  1847)? null : new Occasion(
                "Thomas Alva Edison's Birthday",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Birthday,
                new DateTime(year, (int)Month.February, 11),
                "The inventor and entrepreneur credited with the invention of the electric light bulb and the phonograph. Thomas Alva Edison was born in Milan Ohio on February 11th, 1847."),
            Occasion.AbrahamLincolnsBirthday(year),
            Occasion.GeorgeWashingtonsBirthday(year),
            (year <=  1743)? null : new Occasion(
                "Thomas Jefferson's Birthday",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Birthday,
                new DateTime(year, (int)Month.April, 13),
                "Author of the Declaration of Independence, and a two term president (1801-09). Thomas Jefferson was born at the family home in a one and a half story farmhouse not far from the Virginia wilderness, on April 13, 1743 (April 2, 1743 OS)."),
            (year <=  1955)? null : new Occasion(
                "Albert Einstein's Birthday",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Birthday,
                new DateTime(year, (int)Month.March, 14),
                "The great German-born theoretical physicist.Albert Einstein was Born in Ulm, in the Kingdom of Württemberg in the German Empire, on March 14th 1879."),
            (year <=  1884)? null : new Occasion(
                "Harry S Truman's Birthday",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Birthday,
                new DateTime(year, (int)Month.May, 8),
                "The 33rd president of the U.S. (1945-1953). Harry S Truman presided during the Cold War and Korean War. Known for the New Deal economic policies. He was born in Lamar MO on May 8tth, 1884."),

            // - Microsoft Update dates -

            new(
                "January Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.January, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of January."),
            new(
                "February Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.February, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of February."),
            new(
                "March Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.March, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of March."),
            new(
                "April Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.April, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of April."),
            new(
                "May Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.May, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "Second Tuesday of May."),
            new(
                "June Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.June, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of the Month."),
            new(
                "July Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.July, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of June."),
            new(
                "August Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.August, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of August."),
            new(
                "September Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.September, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of September."),
            new(
                "October Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.October, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of October."),
            new(
                "November Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of November."),
            new(
                "December Patch Tuesday",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.December, 1).FirstInstanceWeekdayOfMonth(2,DayOfWeek.Tuesday),
                "The Second Tuesday of December."),

            // - Algorithm tests -

            new(
                "Test 1",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth(1, DayOfWeek.Sunday),
                "The First Sunday of November"),
            new(
                "Test 2",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth(2, DayOfWeek.Monday),
                "The Second Monday of November"),
            new(
                "Test 3",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth(3, DayOfWeek.Tuesday),
                "The Third Tuesday of November"),
            new(
                "Test 4",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth02(4, DayOfWeek.Wednesday),
                "The Fourth Wednesday of November"),

            new(
                "Last Test 1",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).LastInstanceWeekdayOfMonth(1, DayOfWeek.Sunday),
                "The last Sunday of November"),
            new(
                "Last Test 2",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).LastInstanceWeekdayOfMonth(2, DayOfWeek.Monday),
                "The Second from last Monday of November"),
            new(
                "Last Test 3",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).LastInstanceWeekdayOfMonth(3, DayOfWeek.Tuesday),
                "The Third from last Tuesday of November"),
            new(
                "Last Test 4",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Notification,
                new DateTime(year, (int)Month.November, 1).LastInstanceWeekdayOfMonth(4, DayOfWeek.Wednesday),
                "The Fourth from last Wednesday of November"),

            // United States national food days.
            // https://en.wikipedia.org/wiki/List_of_food_days#United_States
            new("National Creampuff Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 2),
                "National Creampuff Day"),
            new("National Chocolate Covered Cherry Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 3),
                "National Chocolate Covered Cherry Day"),
            new("National Cheese Fondue Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 4),
                "National Cheese Fondue Day"),
            new("National Whipped Cream Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 5),
                "National Whipped Cream Day"),
            new("National Cassoulet Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 9),
                "National Cassoulet Day"),
            new("National Popcorn Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 19),
                "National Popcorn Day"),
            new("Cheese Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 20),
                "Cheese Day"),
            new("National Hot Sauce Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 22),
                "National Hot Sauce Day"),
            new("National Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 23),
                "National Pie Day"),
            new("National Peanut Butter Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 24),
                "National Peanut Butter Day"),
            new("National Chocolate Cake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.January, 27),
                "National Chocolate Cake Day"),
            new("National Tater Tot Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.February, 2),
                "National Tater Tot Day"),
            new("Ice Cream for Breakfast Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.February, 1).FirstInstanceWeekdayOfMonth(1, DayOfWeek.Saturday),
                "Ice Cream for Breakfast Day"),
            new("National Frozen Yogurt Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.February, 1).FirstInstanceWeekdayOfMonth(1, DayOfWeek.Monday),
                "National Frozen Yogurt Day"),
            new("National Pizza Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.February, 9),
                "National Pizza Day"),
            new("National I Want Butterscotch Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.February, 15),
                "National I Want Butterscotch Day"),
            new("National Margarita Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.February, 22),
                "National Margarita Day"),
            new("National Banana Bread Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.February, 23),
                "National Banana Bread Day"),
            new("National Frog Legs Day (Celebration for Leap Day)",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.February, 29),
                "National Frog Legs Day (Celebration for Leap Day)"),
            new("National Peanut Butter Lover's Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 1),
                "National Peanut Butter Lover's Day"),
            new("National Banana Creme Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 2),
                "National Banana Creme Pie Day"),
            new("National Canadian Bacon Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 3),
                "National Canadian Bacon Day"),
            new("National Cheese Doodle Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 5),
                "National Cheese Doodle Day"),
            new("National Crown Roast of Pork Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 7),
                "National Crown Roast of Pork Day"),
            new("National Peanut Cluster Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 8),
                "National Peanut Cluster Day"),
            new("National Pancake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 8),
                "National Pancake Day"),
            new("National Crabmeat Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 9),
                "National Crabmeat Day"),
            new("National Meatball Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 9),
                "National Meatball Day"),
            new("National Blueberry Popover Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 10),
                "National Blueberry Popover Day"),
            new("Oatmeal Nut Waffles Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 11),
                "Oatmeal Nut Waffles Day"),
            new("Johnny Appleseed Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 11),
                "Johnny Appleseed Day"),
            new("National Baked Scallops Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 12),
                "National Baked Scallops Day"),
            new("National Coconut Torte Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 13),
                "National Coconut Torte Day"),
            new("National Corndog Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 22),
                "National Corndog Day"),
            new("National Chips and Dip Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 23),
                "National Chips and Dip Day"),
            new("International Whiskey Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 27),
                "International Whiskey Day"),
            new("National Clams on the Half Shell Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 31),
                "National Clams on the Half Shell Day"),
            new("National Cream Cheese Frosting Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.March, 31),
                "National Cream Cheese Frosting Day"),
            new("National Peanut Butter and Jelly Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 2),
                "National Peanut Butter and Jelly Day"),
            new("National Caramel Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 5),
                "National Caramel Day"),
            new("National Beer Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 7),
                "National Beer Day"),
            new("National Cheese Fondue Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 11),
                "National Cheese Fondue Day"),
            new("National Grilled Cheese Sandwich Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 12),
                "National Grilled Cheese Sandwich Day"),
            new("National Banana Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 15),
                "National Banana Day"),
            new("National Cheeseball Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 17),
                "National Cheeseball Day"),
            new("National Garlic Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 19),
                "National Garlic Day"),
            new("National Rice Ball Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 19),
                "National Rice Ball Day"),
            new("National Jellybean Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 22),
                "National Jellybean Day"),
            new("National Pigs in a Blanket Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 24),
                "National Pigs in a Blanket Day"),
            new("National Zucchini Bread Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 25),
                "National Zucchini Bread Day"),
            new("National Pretzel Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 26),
                "National Pretzel Day"),
            new("National Prime Rib Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 27),
                "National Prime Rib Day"),
            new("National Shrimp Scampi Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.April, 29),
                "National Shrimp Scampi Day"),
            new("National Candied Orange Peel Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 4),
                "National Candied Orange Peel Day"),
            new("National Hoagie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 5),
                "National Hoagie Day"),
            new("National Eat What You Want Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 11),
                "National Eat What You Want Day"),
            new("National Pizza Party Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 1).FirstInstanceWeekdayOfMonth(3, DayOfWeek.Friday),
                "National Pizza Party Day"),
            new("National Walnut Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 17),
                "National Walnut Day"),
            new("National Taffy Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 23),
                "National Taffy Day"),
            new("National Escargot Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 24),
                "National Escargot Day"),
            new("National Brisket Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 28),
                "National Brisket Day"),
            new("National Burger Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.May, 28),
                "National Burger Day"),
            new("National Donut/Doughnut Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 1).FirstInstanceWeekdayOfMonth(1, DayOfWeek.Friday),
                "National Donut/Doughnut Day"),
            new("National Rotisserie Chicken Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 2),
                "National Rotisserie Chicken Day"),
            new("National Rocky Road Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 2),
                "National Rocky Road Day"),
            new("National Chocolate Macaroon Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 3),
                "National Chocolate Macaroon Day"),
            new("National Egg Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 3),
                "National Egg Day"),
            new("National Cheese Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 4),
                "National Cheese Day"),
            new("National Cognac Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 4),
                "National Cognac Day"),
            new("National Gingerbread Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 5),
                "National Gingerbread Day"),
            new("National Moonshine Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 5),
                "National Moonshine Day"),
            new("National Applesauce Cake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 6),
                "National Applesauce Cake Day"),
            new("Chocolate Ice Cream Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 7),
                "Chocolate Ice Cream Day"),
            new("National Iced Tea Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 10),
                "National Iced Tea Day"),
            new("National Corn on the cob day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 11),
                "National Corn on the cob day"),
            new("National German chocolate cake day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 11),
                "National German chocolate cake day"),
            new("National Peanut Butter Cookie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 12),
                "National Peanut Butter Cookie Day"),
            new("National Lobster Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 15),
                "National Lobster Day"),
            new("National Fudge Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 16),
                "National Fudge Day"),
            new("National Eat Your Vegetables Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 17),
                "National Eat Your Vegetables Day"),
            new("National Vanilla Milkshake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 20),
                "National Vanilla Milkshake Day"),
            new("National Ice Cream Soda Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 20),
                "National Ice Cream Soda Day"),
            new("National Kouign Amann Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 20),
                "National Kouign Amann Day"),
            new("National Peaches ‘N’ Cream Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 21),
                "National Peaches ‘N’ Cream Day"),
            new("National Catfish Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 25),
                "National Catfish Day"),
            new("National Chocolate Pudding Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 26),
                "National Chocolate Pudding Day"),
            new("National Orange Blossom Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 27),
                "National Orange Blossom Day"),
            new("National Ceviche Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 28),
                "National Ceviche Day"),
            new("National Tapioca Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 28),
                "National Tapioca Day"),
            new("National Bomb Pop Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.June, 1).LastInstanceWeekdayOfMonth(1, DayOfWeek.Thursday),
                "National Bomb Pop Day"),
            new("National Ice Cream Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 1).FirstInstanceWeekdayOfMonth(3, DayOfWeek.Sunday),
                "National Ice Cream Day"),
            new("National Chili Dog Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 1).FirstInstanceWeekdayOfMonth(4, DayOfWeek.Thursday),
                "National Chili Dog Day"),
            new("National Creative Ice Cream Flavor Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 1),
                "National Creative Ice Cream Flavor Day"),
            new("National Gingersnap Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 1),
                "National Gingersnap Day"),
            new("National Anisette Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 2),
                "National Anisette Day"),
            new("Eat Beans Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 3),
                "Eat Beans Day"),
            new("National Chocolate Wafer Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 3),
                "National Chocolate Wafer Day"),
            new("National Caesar Salad Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 4),
                "National Caesar Salad Day"),
            new("National Spareribs Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 4),
                "National Spareribs Day"),
            new("National Barbecue Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 4),
                "National Barbecue Day"),
            new("National Apple Turnover Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 5),
                "National Apple Turnover Day"),
            new("Take Your Webmaster to Lunch Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 6),
                "Take Your Webmaster to Lunch Day"),
            new("National Fried Chicken Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 6),
                "National Fried Chicken Day"),
            new("Macaroni Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 7),
                "Macaroni Day"),
            new("National Strawberry Sundae Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 7),
                "National Strawberry Sundae Day"),
            new("National Chocolate with Almonds Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 8),
                "National Chocolate with Almonds Day"),
            new("National Sugar Cookie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 9),
                "National Sugar Cookie Day"),
            new("National Piña colada Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 10),
                "National Piña colada Day"),
            new("National Blueberry Muffin Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 11),
                "National Blueberry Muffin Day"),
            new("National Pecan Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 12),
                "National Pecan Pie Day"),
            new("National French Fries Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 13),
                "National French Fries Day"),
            new("National BBQ Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 13),
                "National BBQ Day"),
            new("National Grand Marnier Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 14),
                "National Grand Marnier Day"),
            new("National Mac & Cheese Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 14),
                "National Mac & Cheese Day"),
            new("National Tapioca Pudding Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 15),
                "National Tapioca Pudding Day"),
            new("Gummi Worm Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 15),
                "Gummi Worm Day"),
            new("Fresh Spinach Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 16),
                "Fresh Spinach Day"),
            new("National Corn Fritter Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 16),
                "National Corn Fritter Day"),
            new("National Peach Ice Cream Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 17),
                "National Peach Ice Cream Day"),
            new("National Caviar Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 18),
                "National Caviar Day"),
            new("National Daiquiri Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 19),
                "National Daiquiri Day"),
            new("National Fortune Cookie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 20),
                "National Fortune Cookie Day"),
            new("National Lollipop Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 20),
                "National Lollipop Day"),
            new("National Junk Food Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 21),
                "National Junk Food Day"),
            new("National Penuche Fudge Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 22),
                "National Penuche Fudge Day"),
            new("National Peanut Butter and Chocolate Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 23),
                "National Peanut Butter and Chocolate Day"),
            new("National Vanilla Ice Cream Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 23),
                "National Vanilla Ice Cream Day"),
            new("National Hot Dog Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 23),
                "National Hot Dog Day"),
            new("National Tequila Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 24),
                "National Tequila Day"),
            new("National Drive-Thru Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 24),
                "National Drive-Thru Day"),
            new("National Hot Fudge Sundae Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 25),
                "National Hot Fudge Sundae Day"),
            new("National Coffee Milkshake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 26),
                "National Coffee Milkshake Day"),
            new("National Creme Brulee Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 27),
                "National Creme Brulee Day"),
            new("National Scotch Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 27),
                "National Scotch Day"),
            new("Hamburger Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 28),
                "Hamburger Day"),
            new("National Milk Chocolate Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 28),
                "National Milk Chocolate Day"),
            new("National Lasagna Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 29),
                "National Lasagna Day"),
            new("National Chicken Wing Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 29),
                "National Chicken Wing Day"),
            new("National Cheesecake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 30),
                "National Cheesecake Day"),
            new("National Raspberry Cake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.July, 31),
                "National Raspberry Cake Day"),
            new("National Mustard Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 1).FirstInstanceWeekdayOfMonth(1, DayOfWeek.Saturday),
                "National Mustard Day"),
            new("National Milkshake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 1),
                "National Milkshake Day"),
            new("National Watermelon Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 3),
                "National Watermelon Day"),
            new("National White Wine Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 3),
                "National White Wine Day"),
            new("National S'more Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 10),
                "National S'more Day"),
            new("National Filet Mignon Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 13),
                "National Filet Mignon Day"),
            new("National Creamsicle Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 14),
                "National Creamsicle Day"),
            new("National Lemon Meringue Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 15),
                "National Lemon Meringue Pie Day"),
            new("National Rum Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 16),
                "National Rum Day"),
            new("World Bratwurst Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 16),
                "World Bratwurst Day"),
            new("National Vanilla Custard Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 17),
                "National Vanilla Custard Day"),
            new("National Pinot Noir Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 18),
                "National Pinot Noir Day"),
            new("National Potato Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 19),
                "National Potato Day"),
            new("National Spumoni Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 21),
                "National Spumoni Day"),
            new("National Pecan Torte Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 22),
                "National Pecan Torte Day"),
            new("National Eat A Peach Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 22),
                "National Eat A Peach Day"),
            new("National Sponge Cake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 23),
                "National Sponge Cake Day"),
            new("National Peach Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 24),
                "National Peach Pie Day"),
            new("National Waffle Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 24),
                "National Waffle Day"),
            new("National Banana Split Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 25),
                "National Banana Split Day"),
            new("National Whiskey Sour Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 25),
                "National Whiskey Sour Day"),
            new("National Cherry Popsicle Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 26),
                "National Cherry Popsicle Day"),
            new("National Pots De Creme Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 27),
                "National Pots De Creme Day"),
            new("National Banana Lovers Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 27),
                "National Banana Lovers Day"),
            new("National Cherry Turnover Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 28),
                "National Cherry Turnover Day"),
            new("Crackers Over The Keyboard Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 28),
                "Crackers Over The Keyboard Day"),
            new("More Herbs, Less Salt Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 29),
                "More Herbs, Less Salt Day"),
            new("National Lemon Juice Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 29),
                "National Lemon Juice Day"),
            new("National Chop Suey Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August,29 ),
                "National Chop Suey Day"),
            new("National Toasted Marshmallow Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 30),
                "National Toasted Marshmallow Day"),
            new("Trail Mix Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.August, 31),
                "Trail Mix Day"),
            new("National Cherry Popover Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 1),
                "National Cherry Popover Day"),
            new("National Blueberry Popsicle Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 2),
                "National Blueberry Popsicle Day"),
            new("National Welsh Rarebit Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 2),
                "National Welsh Rarebit Day"),
            new("National Macademia Nut Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 4),
                "National Macademia Nut Day"),
            new("National Cheese Pizza Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 5),
                "National Cheese Pizza Day"),
            new("National Coffee Ice Cream Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 6),
                "National Coffee Ice Cream Day"),
            new("National Beer Lover's Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 7),
                "National Beer Lover's Day"),
            new("National Acorn Squash Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 7),
                "National Acorn Squash Day"),
            new("National Salami Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 7),
                "National Salami Day"),
            new("Wienerschnitzel Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 9),
                "Wienerschnitzel Day"),
            new("National Steak Au Poivre Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 9),
                "National Steak Au Poivre Day"),
            new("National TV Dinner Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 10),
                "National TV Dinner Day"),
            new("National Hot Cross Bun Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 11),
                "National Hot Cross Bun Day"),
            new("National Chocolate Milkshake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 12),
                "National Chocolate Milkshake Day"),
            new("National Peanut Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 13),
                "National Peanut Day"),
            new("International Chocolate Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 13),
                "International Chocolate Day"),
            new("National Eat a Hoagie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 14),
                "National Eat a Hoagie Day"),
            new("National Cream Filled Donut Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 14),
                "National Cream Filled Donut Day"),
            new("National Crème de Menthe Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 15),
                "National Crème de Menthe Day"),
            new("National Double Cheeseburger Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 15),
                "National Double Cheeseburger Day"),
            new("National Linguine Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 15),
                "National Linguine Day"),
            new("National Cheese Toast Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 15),
                "National Cheese Toast Day"),
            new("National Butterscotch Cinnamon Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 15),
                "National Butterscotch Cinnamon Pie Day"),
            new("National Guacamole Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 16),
                "National Guacamole Day"),
            new("National Cinnamon-Raisin Bread Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 16),
                "National Cinnamon-Raisin Bread Day"),
            new("National Apple Dumpling Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 17),
                "National Apple Dumpling Day"),
            new("National Monte Cristo sandwich Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 17),
                "National Monte Cristo sandwich Day"),
            new("National Cheeseburger Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 18),
                "National Cheeseburger Day"),
            new("National Butterscotch Pudding Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 19),
                "National Butterscotch Pudding Day"),
            new("National Pepperoni Pizza Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 20),
                "National Pepperoni Pizza Day"),
            new("National Punch Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 20),
                "National Punch Day"),
            new("National Rum Punch Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 20),
                "National Rum Punch Day"),
            new("National Pecan Cookie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 21),
                "National Pecan Cookie Day"),
            new("National Lobster Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 25),
                "National Lobster Day"),
            new("National Better Breakfast Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 26),
                "National Better Breakfast Day"),
            new("National Pancake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 26),
                "National Pancake Day"),
            new("National Dumpling Day National Chocolate Milk Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 26),
                "National Dumpling Day National Chocolate Milk Day"),
            new("Johnny Appleseed Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 26),
                "Johnny Appleseed Day"),
            new("National Chocolate Milk Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September,27 ),
                "National Chocolate Milk Day"),
            new("National Corned Beef Hash Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 27),
                "National Corned Beef Hash Day"),
            new("Family Day – A Day to Eat Dinner with Your Children",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 28),
                "Family Day – A Day to Eat Dinner with Your Children"),
            new("National Strawberry Cream Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 28),
                "National Strawberry Cream Pie Day"),
            new("National Drink Beer Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 28),
                "National Drink Beer Day"),
            new("National Coffee Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 29),
                "National Coffee Day"),
            new("National Biscotti Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 29),
                "National Biscotti Day"),
            new("National Hot Mulled Cider Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.September, 30),
                "National National Vodka DayHot Mulled Cider Day"),
            new("",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 4),
                "National Vodka Day"),
            new("National Taco Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 4),
                "National Taco Day"),
            new("National Noodle Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 6),
                "National Noodle Day"),
            new("National Sausage Pizza Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 11),
                "National Sausage Pizza Day"),
            new("National Dessert Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 14),
                "National Dessert Day"),
            new("National Chocolate Cupcake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 18),
                "National Chocolate Cupcake Day"),
            new("National Brandied Fruit Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 20),
                "National Brandied Fruit Day"),
            new("National Boston Creme Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 23),
                "National Boston Creme Pie Day"),
            new("National Bologna Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 24),
                "National Bologna Day"),
            new("National Food Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 24),
                "National Food Day"),
            new("National Greasy Food Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 25),
                "National Greasy Food Day"),
            new("National Chocolate day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 28),
                "National Chocolate day"),
            new("National Oatmeal Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 29),
                "National Oatmeal Day"),
            new("Haunted Refrigerator Night",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 30),
                "Haunted Refrigerator Night"),
            new("National Candy Corn Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 30),
                "National Candy Corn Day"),
            new("National Candy Apple Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 31),
                "National Candy Apple Day"),
            new("National Caramel Apple Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.October, 31),
                "National Caramel Apple Day"),
            new("National Vinegar Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 1),
                "National Vinegar Day"),
            new("National Men Make Dinner Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth(1, DayOfWeek.Thursday),
                "National Men Make Dinner Day"),
            new("International Stout Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth(1, DayOfWeek.Thursday),
                "International Stout Day"),
            new("Turkey Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth(4, DayOfWeek.Thursday),
                "Turkey Day"),
            new("Sinkie Day",
                Cultures.en_US,
                OccasionDateType.DynamicAnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 1).FirstInstanceWeekdayOfMonth(4, DayOfWeek.Thursday).AddDays(1),
                "Sinkie Day"),
            new("National French Fried Clam Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 1),
                "National French Fried Clam Day"),
            new("National Cook For Your Pets Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 1),
                "National Cook For Your Pets Day"),
            new("National Deviled Egg Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 2),
                "National Deviled Egg Day"),
            new("National Sandwich Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 3),
                "National Sandwich Day"),
            new("National Candy Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 4),
                "National Candy Day"),
            new("National Eating Healthy Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 4),
                "National Eating Healthy Day"),
            new("National Nachos Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 6),
                "National Nachos Day"),
            new("National Bittersweet Chocolate with Almonds Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 7),
                "National Bittersweet Chocolate with Almonds Day"),
            new("National Harvey Wallbanger Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 8),
                "National Harvey Wallbanger Day"),
            new("Cook Something Bold and Pungent Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 8),
                "Cook Something Bold and Pungent Day"),
            new("National Cappuccino Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 8),
                "National Cappuccino Day"),
            new("National Shot Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 8),
                "National Shot Day"),
            new("National Scrapple Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 9),
                "National Scrapple Day"),
            new("National Vanilla Cupcake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 10),
                "National Vanilla Cupcake Day"),
            new("National Sundae Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 11),
                "National Sundae Day"),
            new("National Pizza with the Works Except Anchovies Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 12),
                "National Pizza with the Works Except Anchovies Day"),
            new("Chicken Soup for the Soul Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 12),
                "Chicken Soup for the Soul Day"),
            new("National Happy Hour Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 12),
                "National Happy Hour Day"),
            new("National Indian Pudding Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 13),
                "National Indian Pudding Day"),
            new("National Pickle Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 14),
                "National Pickle Day"),
            new("National Spicy Guacamole Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 14),
                "National Spicy Guacamole Day"),
            new("National Spicy Hermit Cookie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 15),
                "National Spicy Hermit Cookie Day"),
            new("National Clean Out Your Refrigerator Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 15),
                "National Clean Out Your Refrigerator Day"),
            new("National Fast Food Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 16),
                "National Fast Food Day"),
            new("National Baklava Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 17),
                "National Baklava Day"),
            new("Homemade Bread Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 17),
                "Homemade Bread Day"),
            new("National Vichyssoise Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 18),
                "National Vichyssoise Day"),
            new("National Apple Cider Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 18),
                "National Apple Cider Day"),
            new("Carbonated Beverage with Caffeine Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 19),
                "Carbonated Beverage with Caffeine Day"),
            new("National Peanut Butter Fudge Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 20),
                "National Peanut Butter Fudge Day"),
            new("National Stuffing Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 21),
                "National Stuffing Day"),
            new("National Cashew Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 23),
                "National Cashew Day"),
            new("National Eat A Cranberry Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 23),
                "National Eat A Cranberry Day"),
            new("National Espresso Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 24),
                "National Espresso Day"),
            new("National Parfait Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 25),
                "National Parfait Day"),
            new("National Cake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 26),
                "National Cake Day"),
            new("National French Toast Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 28),
                "National French Toast Day"),
            new("Throw Out Your Leftovers Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 29),
                "Throw Out Your Leftovers Day"),
            new("National Lemon Cream Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 29),
                "National Lemon Cream Pie Day"),
            new("National Chocolates Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 29),
                "National Chocolates Day"),
            new("National Mousse Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.November, 30),
                "National Mousse Day"),
            new("Eat a Red Apple Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 1),
                "Eat a Red Apple Day"),
            new("National Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 1),
                "National Pie Day"),
            new("National Fritters Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 2),
                "National Fritters Day"),
            new("National Cookie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 4),
                "National Cookie Day"),
            new("National Rock Candy Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 5),
                "National Rock Candy Day"),
            new("National Brownie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 8),
                "National Brownie Day"),
            new("National Pastry Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 9),
                "National Pastry Day"),
            new("National Lager Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 10),
                "National Lager Day"),
            new("National Noodle Ring Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 11),
                "National Noodle Ring Day"),
            new("National Have A Bagel Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 11),
                "National Have A Bagel Day"),
            new("National Ice Cream Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 13),
                "National Ice Cream Day"),
            new("National Cupcake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 15),
                "National Cupcake Day"),
            new("National Chocolate-Covered Anything Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 16),
                "National Chocolate-Covered Anything Day"),
            new("National Maple Syrup Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 17),
                "National Maple Syrup Day"),
            new("National Sangria Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 20),
                "National Sangria Day"),
            new("National Hamburger Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 21),
                "National Hamburger Day"),
            new("National Date Nut Bread Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 22),
                "National Date Nut Bread Day"),
            new("National Eggnog Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 24),
                "National Eggnog Day"),
            new("National Pumpkin Pie Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 25),
                "National Pumpkin Pie Day"),
            new("National Fruitcake Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 27),
                "National Fruitcake Day"),
            new("National Bicarbonate of Soda Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 30),
                "National Bicarbonate of Soda Day"),
            new("National Champagne Day",
                Cultures.en_US,
                OccasionDateType.AnnualDate,
                EventType.Holiday,
                new DateTime(year, (int)Month.December, 31),
                "National Champagne Day"),
        ];
        HolidayList.RemoveAll(a => a is null);
    }

    /// <summary>
    /// The is holiday.
    /// </summary>
    /// <param name="currentDate">The currentDate.</param>
    /// <returns>The <see cref="Tuple{T1, T2}"/>.</returns>
    /// <remarks><para>http://solidcoding.blogspot.com/2007/11/c30-extension-method-to-check-holidays.html</para></remarks>
    public (bool, List<Occasion>) IsHoliday(DateTime currentDate)
    {
        var occasions = new List<Occasion>(
            from h in HolidayList
            where h.Date.Value.Month == currentDate.Month
            && h.Date.Value.Day == currentDate.Day
            select h
            );

        if (occasions.Count > 0)
        {
            return (true, occasions);
        }

        return (false, null);
    }
}
